import { App, TFile, Notice } from 'obsidian';
import { AnnotationStore, Annotation } from './annotation-store';

/**
 * Export all feedback annotations for the current file
 * as a structured Markdown document.
 */
export async function exportFeedback(
  app: App,
  store: AnnotationStore,
  filePath: string
): Promise<void> {
  if (!filePath) {
    new Notice('Open a Markdown note first');
    return;
  }

  const annotations = await store.getAnnotations(filePath);

  if (annotations.length === 0) {
    new Notice('No feedback annotations in the current note');
    return;
  }

  const fileName = filePath.split('/').pop() || filePath;
  const now = new Date().toLocaleString();

  let content = `# Feedback Summary\n\n`;
  content += `> Source file: ${fileName}\n`;
  content += `> File path: ${filePath}\n`;
  content += `> Annotation count: ${annotations.length}\n`;
  content += `> Exported at: ${now}\n\n`;
  content += `---\n\n`;

  annotations.forEach((ann, i) => {
    content += `## Feedback ${i + 1}\n\n`;
    content += `**Original text**: "${ann.originalText}"\n\n`;
    content += `**Location**: line ${ann.lineStart}`;
    if (ann.lineStart !== ann.lineEnd) {
      content += ` - line ${ann.lineEnd}`;
    }
    content += `\n\n`;
    content += `**Feedback**: ${ann.feedback}\n\n`;
    content += `**Timestamp**: ${new Date(ann.timestamp).toLocaleString()}\n\n`;
    content += `---\n\n`;
  });

  // Create the export file in the same directory
  const exportPath = filePath.replace(/\.md$/, '.feedback_export.md');

  const existingFile = app.vault.getAbstractFileByPath(exportPath);
  if (existingFile && existingFile instanceof TFile) {
    await app.vault.modify(existingFile, content);
  } else {
    await app.vault.create(exportPath, content);
  }

  new Notice(`Feedback exported to: ${exportPath}`);

  // Open the exported file in a new leaf
  const file = app.vault.getAbstractFileByPath(exportPath);
  if (file && file instanceof TFile) {
    const leaf = app.workspace.getLeaf('tab');
    await leaf.openFile(file);
  }
}

/**
 * Append feedback annotations to a local feedback_log.md review log.
 */
export async function appendFeedbackToReviewLog(
  app: App,
  store: AnnotationStore,
  filePath: string
): Promise<void> {
  if (!filePath) {
    new Notice('Open a Markdown note first');
    return;
  }

  const annotations = await store.getAnnotations(filePath);

  if (annotations.length === 0) {
    new Notice('No feedback annotations in the current note');
    return;
  }

  const fileName = filePath.split('/').pop() || filePath;
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  // Build feedback summary text
  const feedbackSummary = annotations
    .map((ann, i) => {
      const shortOriginal = ann.originalText.length > 40
        ? ann.originalText.substring(0, 40) + '...'
        : ann.originalText;
      return `${i + 1}) "${shortOriginal}" -> ${ann.feedback}`;
    })
    .join('; ');

  const logEntry = `| ${dateStr} ${timeStr} | ${fileName} | ${annotations.length} | ${feedbackSummary} | Pending |`;

  // Find feedback_log.md - search in same directory, then parent directories
  const dir = filePath.substring(0, filePath.lastIndexOf('/'));
  const searchPaths = [
    `${dir}/feedback_log.md`,
    // Try parent directory for project-level review logs.
    `${dir.substring(0, dir.lastIndexOf('/'))}/feedback_log.md`,
  ];

  let logFile: TFile | null = null;
  let logPath = '';

  for (const path of searchPaths) {
    const file = app.vault.getAbstractFileByPath(path);
    if (file && file instanceof TFile) {
      logFile = file;
      logPath = path;
      break;
    }
  }

  if (logFile) {
    // Append to existing log
    const existingContent = await app.vault.read(logFile);
    await app.vault.modify(logFile, existingContent + '\n' + logEntry);
    new Notice(`Feedback appended to: ${logPath}`);
  } else {
    // Create new feedback_log.md in same directory
    logPath = `${dir}/feedback_log.md`;
    const header =
      `# Feedback Review Log\n\n` +
      `> Lightweight review log generated by Inline Feedback.\n\n` +
      `---\n\n` +
      `| Date | Source note | Count | Feedback summary | Status |\n` +
      `|------|-------------|-------|------------------|--------|\n` +
      logEntry + '\n';
    await app.vault.create(logPath, header);
    new Notice(`Created and appended to: ${logPath}`);
  }
}
